name: ci

env:
  CMAKE_BUILD_TYPE: Release
  CMAKE_BUILD_PARALLEL_LEVEL: 4
  CTEST_PARALLEL_LEVEL: 0

on:
  push:
    paths:
    - "**.py"
    - .github/workflows/ci.yml

jobs:

  core:
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-latest]

    runs-on: ${{ matrix.os }}

    env:
      FC: gfortran-14

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - run: pip install .[tests,lint]

    - run: flake8
    - run: mypy

    - run: pytest
